### ISSUE TITLE
Разработать мини-игры

### ISSUE THREAD

**Issue by DashaPavlova** [DashaPavlova/Laboratornay7#13]
Написать программные коды на языке с# в Windows Forms в программе Visual studia для 7 мини-игр основной игры, сюжеты миниигр и картинки для них взять из 1 спринта из задач 6 и 5.

**Comment by itSveta** [comment]
Исходники на диске: https://drive.google.com/drive/folders/1rjlrOtc4DyUWHDEakqazZFf_FVQDIXzv
