### ISSUE TITLE
Смонтировать видео для начала игры

### ISSUE THREAD

**Issue by DashaPavlova** [DashaPavlova/Laboratornay7#16]
Взяв сюжет землетрясения с помощью картинок и музыки показать происшествие, чтобы игрок понял пред историю игры. Картинки взять из задачи 17, музыку из задачи 18. Желательный формат видео mp4.

**Comment by dreaer-cyber** [comment]
Видео
[З.zip](https://github.com/DashaPavlova/Laboratornay7/files/4707912/default.zip)
