### ISSUE TITLE
Подготовить картинки для видео

### ISSUE THREAD

**Issue by DashaPavlova** [DashaPavlova/Laboratornay7#17]
Подобрать картинки для изображения землетрясения, чтобы показать игроку пред историю  игры. 

- Картинки могут быть взяты из Pixabay или Pexels или с любого другого бесплатного источника. 

- Желаемый формат png или jpg.

**Comment by dreaer-cyber** [comment]
![Без имени-3](https://user-images.githubusercontent.com/61991772/83356740-b5cd0b80-a370-11ea-9abc-34679b048055.png)
![Без имени-2](https://user-images.githubusercontent.com/61991772/83356742-b6fe3880-a370-11ea-8bc7-f3b7255447d9.png)
Картинки
