### ISSUE TITLE
Нарисовать основную картину игры

### ISSUE THREAD

**Issue by DashaPavlova** [DashaPavlova/Laboratornay7#19]
- нарисовать 9 этапов прорисовки основной картины игры которая будет прорисовываться в процессе прохождения мини-игр (белое полотно в начале, черно-белый рисунок, добавление цветов, итоговое изображение)

**Comment by EluanOku** [comment]
Нарисованы этапы прорисовки картины для игры

![холст](https://user-images.githubusercontent.com/61930343/83309857-09294780-a213-11ea-89cf-a2dc3f93e721.png)
![картина 1](https://user-images.githubusercontent.com/61930343/83309829-f6af0e00-a212-11ea-84d6-94803cb2885e.png)
![картина 2](https://user-images.githubusercontent.com/61930343/83309833-f9a9fe80-a212-11ea-8e20-f1e62c59a7f3.png)
![картина 3](https://user-images.githubusercontent.com/61930343/83309836-fb73c200-a212-11ea-9809-e81dc96815f6.png)
![картина 4](https://user-images.githubusercontent.com/61930343/83309842-fdd61c00-a212-11ea-9b55-2c1447335c06.png)
![картина 5](https://user-images.githubusercontent.com/61930343/83309844-ff9fdf80-a212-11ea-983f-9cd24951ff47.png)
![картина 6](https://user-images.githubusercontent.com/61930343/83309845-0169a300-a213-11ea-8cde-873b7b87ffc4.png)
![картина без рамки](https://user-images.githubusercontent.com/61930343/83309848-03cbfd00-a213-11ea-8a99-cd93b6cc0256.png)
![картина](https://user-images.githubusercontent.com/61930343/83309852-0595c080-a213-11ea-865c-b14b084db51c.png)
