### ISSUE TITLE
Продумать образы персонажей

### ISSUE THREAD

**Issue by DashaPavlova** [DashaPavlova/Laboratornay7#3]
Сделать подробное описание персонажей по которому дизайнеры смогут их нарисовать. Либо найти картинки по которым они будут созданы.  Картинки могут быть взяты из Pixabay или Pexels или с любого другого бесплатного источника. Желаемый формат png или jpg.

**Comment by AndreyMaraj** [comment]
![C1AC8FB8-A6DF-4FB2-876E-0FB69743BB56](https://user-images.githubusercontent.com/62002297/82762399-7bf88400-9e09-11ea-854a-a7049c1553c4.jpeg)
![Uploading 8A6CE638-35FA-4F89-98F2-17AC1D668A59.jpeg…]()

**Comment by AndreyMaraj** [comment]
![E7BA6247-0572-4820-9DBE-9882183A7AB8](https://user-images.githubusercontent.com/62002297/82762414-92064480-9e09-11ea-88b9-b5951489b51b.jpeg)
![Uploading 479D8266-E80A-4DE8-AE5F-6A7EBC8987BC.jpeg…]()

**Comment by AndreyMaraj** [comment]
![23782D1D-9FA2-4DC2-BC6B-6E85D02D0E61](https://user-images.githubusercontent.com/62002297/82762433-a21e2400-9e09-11ea-8f20-23162ae19c1f.jpeg)
