### ISSUE TITLE
Написать сценарий игры

### ISSUE THREAD

**Issue by DashaPavlova** [DashaPavlova/Laboratornay7#4]
- Прописать диалоги игры. 

- Описать действия персонажей. 

- Написать полный сюжет игры.
Игра должна быть обучающей по предмету изобразительное искусство для совершенствования знаний в данной предметной области.

**Comment by AndreyMaraj** [comment]
Квест-игра "Случай в картинной галерее"
Звук землетрясения. Появляется следователь. Просит помощи игрока найти пропавшие составляющие части картины. Появляется карта игры, на которой изображены (спрятаны) составляющие части картины. Игрок последовательно выбирает один из предметов и начинается мини-игра. При успешном прохождении мини-игры найденная игроком часть автоматически заполняется на картине и показывается игроку, а сам предмет на карте помечается как выполненный. В противном случае предлагается пройти игру заново. По прохождению всех мини-игр появляется картинка с галереей вместе с картиной, у которой потерялись части. Выводится сообщение о поздравлении и прохождении квест-игры.

**Comment by AndreyMaraj** [comment]
Квест-игра "Случай в картинной галерее"
Звук землетрясения. Появляется следователь с монологом: «Как хорошо, что вы здесь! Нам просто необходима Ваша помощь. После этого жуткого землятресения все элементы самой дорогой картины в мире разлетелись. Больше человек - больше вероятность найти. Приступай!». Появляется карта игры, на которой изображены (спрятаны) составляющие части картины. Игрок последовательно выбирает один из предметов и начинается мини-игра. При успешном прохождении мини-игры найденная игроком часть автоматически заполняется на картине и показывается игроку, а сам предмет на карте помечается как выполненный. В противном случае предлагается пройти игру заново. По прохождению всех мини-игр появляется картинка с галереей вместе с картиной, у которой потерялись части. Выводится сообщение о поздравлении и прохождении квест-игры.
