### ISSUE TITLE
Продумать сюжеты миниигр

### ISSUE THREAD

**Issue by DashaPavlova** [DashaPavlova/Laboratornay7#5]
Продумать сюжеты 7 мини-игр. Подробно описать действия персонажей и правила мини-игр, для дальнейшего написания их в программном коде.  Мини-игры должны быть обучающими по предмету изобразительное искусство, т.е. должны рассказывать об известных картинах или авторах, а так же проверять знания по изо.

**Comment by AndreyMaraj** [comment]
Мини-игры:
1) Игроку необходимо пройти вертикальные препятствия, используя клавиши вверх и вниз, летающим героем-кляксой. При столкновением с препятствием мини-игра начинается заново. Мини-игра заканчивается, когда все препятствия преодолены.
2) Игроку необходимо управлять героем-баночкой краски. Ему надо пройти до финиша по вертикальной плоскости, не задев опасные препятствия. При столкновении с опасным препятствием мини-игра начинается заново. Дойдя до финиша, мини-игра завершается.
3) Игроку необходимо составить целую картину из ее кусочков. При правильном сборе пазла мини-игра заканчивается.
4) Игроку необходимо пройти тест с использованием вопросов по теме "Известные картины". После правильного прохождения теста мини-игра заканчивается.
5) Игроку необходимо выиграть игру в "Крестики-Нолики". Он может играть как и против компьютера, так и против друга. В мини-игру можно играть несколько раз.
6) Игроку необходимо сыграть в игру "Пятнашки". Правила игры заключаются в размещении пронумерованных блоков в порядке возрастания.
7) Игроку необходимо пройти тест с использованием вопросов по теме "Известные художники". После правильного прохождения теста мини-игра заканчивается.
8) Игроку необходимо правильно сопоставить названию картины ее изображение среди предложенных вариантов.
9) Игра "Змейка"
10) Игра "Арканойд"
