### ISSUE TITLE
Подобрать картинки для миниигр

### ISSUE THREAD

**Issue by DashaPavlova** [DashaPavlova/Laboratornay7#6]
Подобрать минимум по 5 картин любых художников для фонов и других объектов мини-игр, чтобы дизайнеры дальше отредактировали их. Картинки могут быть взяты из Pixabay или Pexels или с любого другого бесплатного источника. Желаемый формат png или jpg.

**Comment by AndreyMaraj** [comment]
![FEA0037B-5A1E-4F55-968C-5917CCC4EE25](https://user-images.githubusercontent.com/62002297/82737157-82b6c680-9d37-11ea-9cbb-4e537c392865.jpeg)
![F03E92CE-EAF6-4138-B91B-3A743010AD82](https://user-images.githubusercontent.com/62002297/82737162-864a4d80-9d37-11ea-878f-5b94db1b1c56.jpeg)
![A2E89F94-1390-459B-952D-B17F6A07EBE1](https://user-images.githubusercontent.com/62002297/82737163-86e2e400-9d37-11ea-9f06-26408eded3c2.jpeg)
![7C625C58-57C9-48CE-8992-EC2041971DDA](https://user-images.githubusercontent.com/62002297/82737165-877b7a80-9d37-11ea-8802-8f8f1d9a3d33.jpeg)
![E03BBE51-1378-4F47-BAD6-94F3FEE43C1A](https://user-images.githubusercontent.com/62002297/82737166-88141100-9d37-11ea-8416-557f6dc62087.jpeg)

**Comment by AndreyMaraj** [comment]
![BCA6C36A-B0E2-4DB4-B81E-EEDCEFC48FBE](https://user-images.githubusercontent.com/62002297/82737355-41271b00-9d39-11ea-85a8-b356f9d4a8d9.jpeg)
![A5945988-A3AE-49D6-927C-B4C71DD39CD1](https://user-images.githubusercontent.com/62002297/82737357-46846580-9d39-11ea-983a-7bcfe2d1a651.jpeg)
![EB0C87A5-8A59-46BF-BDC3-ECA37A083B61](https://user-images.githubusercontent.com/62002297/82737365-4ab08300-9d39-11ea-8f65-a61c0d552c28.jpeg)
![A6AC82EB-B26B-40A5-83CA-FE4AD8DEF15D](https://user-images.githubusercontent.com/62002297/82737366-4b491980-9d39-11ea-811a-14e3448326f5.jpeg)
![D438A35F-CFFB-4A54-A1DE-F238FC519853](https://user-images.githubusercontent.com/62002297/82737367-4be1b000-9d39-11ea-865f-4305beb6d0dc.jpeg)
