### ISSUE TITLE
Продумать внешний вид игры

### ISSUE THREAD

**Issue by DashaPavlova** [DashaPavlova/Laboratornay7#8]
- подобрать фон для будущей игры(сделать рисунок карты галереи с 9 отметками для дальнейшего перехода по мини-играм и стены на которой была "разрушена" картина), формат изображений png

- положение персонажей
нарисовать основные макеты игры сначала черновик,, потом итоговый вариант в программе Figma

**Comment by EluanOku** [comment]
Нарисован первый макет
![ааа](https://user-images.githubusercontent.com/61930343/82607159-f84c5680-9bc0-11ea-8925-c5cd42e5dbe9.png)

**Comment by EluanOku** [comment]
Прорисована карта

![карта](https://user-images.githubusercontent.com/61930343/82737332-176df400-9d39-11ea-9763-1954e391d69b.png)

**Comment by EluanOku** [comment]
Нарисован фон - галлерея

![стена](https://user-images.githubusercontent.com/61930343/82737358-46846580-9d39-11ea-808a-7239976847aa.png)

**Comment by AndreyMaraj** [comment]
https://www.figma.com/proto/1VxqyDtkoNzVjGsP3SizNu/Game?node-id=1%3A2&scaling=scale-down
