### ISSUE TITLE
Доработать картинки для миниигр

### ISSUE THREAD

**Issue by DashaPavlova** [DashaPavlova/Laboratornay7#9]
Отредактировать картинки по требованиям сюжета мини-игр.(Например разрезать на кусочки или дорисовать какие-то объекты, некоторые объекты можно нарисовать). Формат итоговых изображений png.

**Comment by EluanOku** [comment]
Нарисованы некоторые элементы для игры
![палитка](https://user-images.githubusercontent.com/61930343/82755499-8c463a00-9ddc-11ea-86c6-44012bebd18f.png)
![кисть](https://user-images.githubusercontent.com/61930343/82755502-92d4b180-9ddc-11ea-950c-9b823f02ee9d.png)
![image](https://user-images.githubusercontent.com/61930343/82755528-c1eb2300-9ddc-11ea-9011-1509bb698e82.png)

**Comment by EluanOku** [comment]
Нарисованы фоны для мини-игр

![пустыня](https://user-images.githubusercontent.com/61930343/83359185-4d3a5a80-a381-11ea-8534-c2b35e0314f8.png)
![комната](https://user-images.githubusercontent.com/61930343/83359193-59261c80-a381-11ea-8cf3-0bd9355138c9.png)
![лес](https://user-images.githubusercontent.com/61930343/83359201-693dfc00-a381-11ea-8cfc-9542678d060c.png)
![поле](https://user-images.githubusercontent.com/61930343/83359208-76f38180-a381-11ea-99df-59254b01206e.png)
![ночь](https://user-images.githubusercontent.com/61930343/83359223-9db1b800-a381-11ea-9e2e-fd7470cbd1e7.png)
